apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-app
spec:
  rules:
    - host: foo.bar.com
      http:
        paths:
          - path: /bar
            pathType: Prefix 
            backend:
              service:
                name: spring-boot-app
                port:
                  number: 8080
